import type { MessageKey } from "@/shared/i18n/messages/types";

// StandaloneMockupView(단독 목업 프로세스)에서만 쓰는 템플릿별 구체적 제목
// lookup -- slug -> 메시지 키. MockupStudioView(프로젝트 흐름 마지막 목업
// 단계)는 여전히 MOCKUP_CATEGORY_LABEL_KEYS + 인덱스 번호만 쓰고 이 파일과
// 무관하다(관리용 원문 노출 금지 원칙 유지).
export const MOCKUP_TEMPLATE_TITLE_KEYS: Record<string, MessageKey> = {
  "business-card-realestate": "mockupTemplateTitles.businessCardRealestate",
  "business-card-lawyer": "mockupTemplateTitles.businessCardLawyer",
  "business-card-photographer": "mockupTemplateTitles.businessCardPhotographer",
  "business-card-consultant": "mockupTemplateTitles.businessCardConsultant",
  "business-card-architect": "mockupTemplateTitles.businessCardArchitect",
  "business-card-wedding-planner": "mockupTemplateTitles.businessCardWeddingPlanner",
  "business-card-personal-trainer": "mockupTemplateTitles.businessCardPersonalTrainer",
  "business-card-therapist": "mockupTemplateTitles.businessCardTherapist",
  "business-card-realestate-ko": "mockupTemplateTitles.businessCardRealestateKo",
  "business-card-hair-ko": "mockupTemplateTitles.businessCardHairKo",
  "signboard-coffee-roastery": "mockupTemplateTitles.signboardCoffeeRoastery",
  "signboard-bakery": "mockupTemplateTitles.signboardBakery",
  "signboard-hair-salon": "mockupTemplateTitles.signboardHairSalon",
  "signboard-flower-shop": "mockupTemplateTitles.signboardFlowerShop",
  "signboard-gym": "mockupTemplateTitles.signboardGym",
  "signboard-bookstore": "mockupTemplateTitles.signboardBookstore",
  "signboard-restaurant": "mockupTemplateTitles.signboardRestaurant",
  "signboard-boutique": "mockupTemplateTitles.signboardBoutique",
  "signboard-cafe-ko": "mockupTemplateTitles.signboardCafeKo",
  "signboard-vet-ko": "mockupTemplateTitles.signboardVetKo",
  "mobile-app-fitness": "mockupTemplateTitles.mobileAppFitness",
  "mobile-app-food-delivery": "mockupTemplateTitles.mobileAppFoodDelivery",
  "mobile-app-banking": "mockupTemplateTitles.mobileAppBanking",
  "mobile-app-meditation": "mockupTemplateTitles.mobileAppMeditation",
  "mobile-app-travel": "mockupTemplateTitles.mobileAppTravel",
  "mobile-app-ecommerce": "mockupTemplateTitles.mobileAppEcommerce",
  "mobile-app-social": "mockupTemplateTitles.mobileAppSocial",
  "mobile-app-productivity": "mockupTemplateTitles.mobileAppProductivity",
  "mobile-app-delivery-ko": "mockupTemplateTitles.mobileAppDeliveryKo",
  "mobile-app-fitness-ko": "mockupTemplateTitles.mobileAppFitnessKo",
  "website-hero-saas": "mockupTemplateTitles.websiteHeroSaas",
  "website-hero-law-firm": "mockupTemplateTitles.websiteHeroLawFirm",
  "website-hero-interior": "mockupTemplateTitles.websiteHeroInterior",
  "website-hero-wedding-photo": "mockupTemplateTitles.websiteHeroWeddingPhoto",
  "website-hero-fitness-studio": "mockupTemplateTitles.websiteHeroFitnessStudio",
  "website-hero-consulting": "mockupTemplateTitles.websiteHeroConsulting",
  "website-hero-fashion-ecommerce": "mockupTemplateTitles.websiteHeroFashionEcommerce",
  "website-hero-architecture": "mockupTemplateTitles.websiteHeroArchitecture",
  "website-hero-startup-ko": "mockupTemplateTitles.websiteHeroStartupKo",
  "website-hero-shop-ko": "mockupTemplateTitles.websiteHeroShopKo",
  "brochure-real-estate": "mockupTemplateTitles.brochureRealEstate",
  "brochure-spa-wellness": "mockupTemplateTitles.brochureSpaWellness",
  "brochure-law-firm": "mockupTemplateTitles.brochureLawFirm",
  "brochure-restaurant": "mockupTemplateTitles.brochureRestaurant",
  "brochure-architecture": "mockupTemplateTitles.brochureArchitecture",
  "brochure-travel-agency": "mockupTemplateTitles.brochureTravelAgency",
  "brochure-medical-clinic": "mockupTemplateTitles.brochureMedicalClinic",
  "brochure-university": "mockupTemplateTitles.brochureUniversity",
  "brochure-real-estate-ko": "mockupTemplateTitles.brochureRealEstateKo",
  "brochure-travel-ko": "mockupTemplateTitles.brochureTravelKo",
  "poster-yoga-studio": "mockupTemplateTitles.posterYogaStudio",
  "poster-concert": "mockupTemplateTitles.posterConcert",
  "poster-restaurant-opening": "mockupTemplateTitles.posterRestaurantOpening",
  "poster-gym": "mockupTemplateTitles.posterGym",
  "poster-art-exhibition": "mockupTemplateTitles.posterArtExhibition",
  "poster-cafe-menu": "mockupTemplateTitles.posterCafeMenu",
  "poster-farmers-market": "mockupTemplateTitles.posterFarmersMarket",
  "poster-fashion-sale": "mockupTemplateTitles.posterFashionSale",
  "poster-cafe-ko": "mockupTemplateTitles.posterCafeKo",
  "poster-performance-ko": "mockupTemplateTitles.posterPerformanceKo",
  "package-skincare": "mockupTemplateTitles.packageSkincare",
  "package-coffee-beans": "mockupTemplateTitles.packageCoffeeBeans",
  "package-tea": "mockupTemplateTitles.packageTea",
  "package-snacks": "mockupTemplateTitles.packageSnacks",
  "package-supplements": "mockupTemplateTitles.packageSupplements",
  "package-candle": "mockupTemplateTitles.packageCandle",
  "package-chocolate": "mockupTemplateTitles.packageChocolate",
  "package-honey": "mockupTemplateTitles.packageHoney",
  "package-cosmetics-ko": "mockupTemplateTitles.packageCosmeticsKo",
  "package-tea-ko": "mockupTemplateTitles.packageTeaKo",
  "leaflet-dental-clinic": "mockupTemplateTitles.leafletDentalClinic",
  "leaflet-gym-membership": "mockupTemplateTitles.leafletGymMembership",
  "leaflet-real-estate-listing": "mockupTemplateTitles.leafletRealEstateListing",
  "leaflet-spa-promotion": "mockupTemplateTitles.leafletSpaPromotion",
  "leaflet-restaurant-menu": "mockupTemplateTitles.leafletRestaurantMenu",
  "leaflet-salon-services": "mockupTemplateTitles.leafletSalonServices",
  "leaflet-pilates-class": "mockupTemplateTitles.leafletPilatesClass",
  "leaflet-bakery": "mockupTemplateTitles.leafletBakery",
  "leaflet-clinic-ko": "mockupTemplateTitles.leafletClinicKo",
  "leaflet-gym-ko": "mockupTemplateTitles.leafletGymKo",
  "banner-sale-event": "mockupTemplateTitles.bannerSaleEvent",
  "banner-grand-opening": "mockupTemplateTitles.bannerGrandOpening",
  "banner-restaurant-promo": "mockupTemplateTitles.bannerRestaurantPromo",
  "banner-fitness-challenge": "mockupTemplateTitles.bannerFitnessChallenge",
  "banner-bookstore-event": "mockupTemplateTitles.bannerBookstoreEvent",
  "banner-cafe": "mockupTemplateTitles.bannerCafe",
  "banner-real-estate-openhouse": "mockupTemplateTitles.bannerRealEstateOpenhouse",
  "banner-wedding-expo": "mockupTemplateTitles.bannerWeddingExpo",
  "banner-open-ko": "mockupTemplateTitles.bannerOpenKo",
  "banner-sale-ko": "mockupTemplateTitles.bannerSaleKo",
  "uniform-cafe-barista": "mockupTemplateTitles.uniformCafeBarista",
  "uniform-cafe-ko": "mockupTemplateTitles.uniformCafeKo",
  "uniform-chef": "mockupTemplateTitles.uniformChef",
  "uniform-gym-trainer": "mockupTemplateTitles.uniformGymTrainer",
  "uniform-hotel-staff": "mockupTemplateTitles.uniformHotelStaff",
  "uniform-medical-staff": "mockupTemplateTitles.uniformMedicalStaff",
  "uniform-retail-store": "mockupTemplateTitles.uniformRetailStore",
  "uniform-salon-ko": "mockupTemplateTitles.uniformSalonKo",
  "uniform-salon-stylist": "mockupTemplateTitles.uniformSalonStylist",
  "uniform-spa-therapist": "mockupTemplateTitles.uniformSpaTherapist",
};

/** slug가 매핑에 없으면(관리자가 나중에 새 템플릿을 추가한 경우) 카테고리 라벨로 안전하게 대체한다. */
export function mockupTemplateTitleKey(slug: string, fallback: MessageKey): MessageKey {
  return MOCKUP_TEMPLATE_TITLE_KEYS[slug] ?? fallback;
}
