import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";

/**
 * 2026-07-28: 업종 카탈로그(Task: "Aster 업종 시스템 개선"). 이전엔
 * interviewQuestions.ts의 하드코딩된 INDUSTRY_OPTIONS(19개, "기타" 포함)
 * 뿐이었다 -- Style/MockupTemplate과 동일한 패턴으로 DB 이관해 최소 50개로
 * 확장하고, admin(/ops-portal-7x2q/industries)에서 코드 배포 없이 추가/수정할
 * 수 있게 한다. `name`은 인터뷰 answers.industry에 그대로 저장되는 원문이라,
 * 기존 18개 실제 업종(INDUSTRY_OPTIONS 중 "기타" 제외)은 문자열을 정확히
 * 그대로 보존한다 -- 값이 바뀌면 promptBuilder.ts의 INDUSTRY_STYLE_TEMPLATES와
 * industryQuestions.ts의 키워드 매칭이 조용히 깨진다. Re-run with
 * `npm run prisma:seed-industries`; upsert by name, 안전하게 재실행 가능.
 */

interface IndustryDef {
  name: string;
  seoSlug: string;
  category: string;
  description: string;
  recommendedColors: string[];
  recommendedLogoStyles: string[];
  recommendedTypography: string[];
  recommendedPersonality: string[];
  recommendedKeywords: string[];
}

const INDUSTRIES: IndustryDef[] = [
  {
    name: "카페/커피",
    seoSlug: "coffee-shop",
    category: "F&B",
    description: "따뜻한 일상과 머무는 시간을 파는 업종으로, 공간의 분위기와 원두의 취향이 곧 브랜드 정체성이 됩니다. 과하지 않게 감각적이면서 편안한 인상을 주는 브랜딩을 선호합니다.",
    recommendedColors: ["#6F4E37","#D9C7B0","#2F3A34","웜 브라운","크림 베이지"],
    recommendedLogoStyles: ["미니멀","오가닉"],
    recommendedTypography: ["여백이 넉넉한 산세리프","소문자 위주의 로고타이프","손글씨 느낌의 포인트 서체"],
    recommendedPersonality: ["편안한","감각적인","따뜻한","일상적인"],
    recommendedKeywords: ["카페","커피","커피숍","에스프레소","브런치 카페","디저트 카페"],
  },
  {
    name: "레스토랑/외식",
    seoSlug: "restaurant",
    category: "F&B",
    description: "요리의 개성과 접객 경험을 동시에 전달해야 하는 업종으로, 메뉴판과 간판, 배달 패키지까지 일관된 인상이 중요합니다. 식욕을 자극하면서도 격을 갖춘 표현을 선호합니다.",
    recommendedColors: ["#8C2F2F","#1F1B18","딥 버건디","웜 아이보리"],
    recommendedLogoStyles: ["클래식","에디토리얼"],
    recommendedTypography: ["세리프 클래식체","자간이 넓은 대문자 로고타이프","간결한 산세리프 본문체"],
    recommendedPersonality: ["정성스러운","환대하는","풍미 있는","신뢰감 있는"],
    recommendedKeywords: ["레스토랑","식당","외식","맛집","다이닝","한식당"],
  },
  {
    name: "식품/농수산물",
    seoSlug: "food-agriculture",
    category: "F&B",
    description: "산지와 원물의 신선함을 증명해야 하는 업종으로, 포장재와 라벨에서 재료의 정직함이 먼저 읽혀야 합니다. 자연 소재를 연상시키는 색과 형태가 잘 맞습니다.",
    recommendedColors: ["#4A7C3F","#D9B26A","#F5EFE1","세이지 그린","어스 브라운"],
    recommendedLogoStyles: ["오가닉","클래식"],
    recommendedTypography: ["손그림 느낌의 워드마크","친근한 세리프","라벨용 고딕 본문체"],
    recommendedPersonality: ["정직한","신선한","건강한","소박한"],
    recommendedKeywords: ["식품","농산물","수산물","산지직송","먹거리","가공식품"],
  },
  {
    name: "베이커리",
    seoSlug: "bakery",
    category: "F&B",
    description: "매일 굽는 신선함과 손의 정성을 파는 업종으로, 진열대와 포장지, 간판에서 따뜻한 질감이 그대로 느껴져야 합니다. 손맛을 연상시키는 부드러운 표현을 선호합니다.",
    recommendedColors: ["#C98B4B","#F3E6D0","#6B4A2F","버터 크림","웜 브라운"],
    recommendedLogoStyles: ["오가닉","클래식"],
    recommendedTypography: ["손글씨 느낌의 스크립트체","따뜻한 세리프 워드마크","포장 라벨용 산세리프"],
    recommendedPersonality: ["따뜻한","정성스러운","소박한","친근한"],
    recommendedKeywords: ["베이커리","빵집","제과","제빵","페이스트리","브레드"],
  },
  {
    name: "커피 로스터리",
    seoSlug: "coffee-roastery",
    category: "F&B",
    description: "생두 선별과 로스팅 철학이 곧 제품 경쟁력인 업종으로, 원두 봉투 위 라벨 체계가 브랜드의 얼굴이 됩니다. 전문성이 느껴지는 정보 중심의 디자인을 선호합니다.",
    recommendedColors: ["#3B2A20","#B4552D","#7D8A6A","다크 로스트 브라운","크래프트 크림"],
    recommendedLogoStyles: ["미니멀","에디토리얼"],
    recommendedTypography: ["스탬프 느낌의 대문자 워드마크","정보 정리에 강한 산세리프","클래식 세리프 포인트"],
    recommendedPersonality: ["전문적인","장인정신 있는","진중한","깊이 있는"],
    recommendedKeywords: ["로스터리","원두","커피 로스팅","스페셜티 커피","생두","드립커피"],
  },
  {
    name: "디저트/아이스크림",
    seoSlug: "ice-cream-dessert",
    category: "F&B",
    description: "맛보다 눈으로 먼저 소비되는 업종으로, 색과 형태의 즐거움이 구매를 이끕니다. 제품 사진과 함께 놓였을 때 흥이 나는 밝은 아이덴티티를 선호합니다.",
    recommendedColors: ["#F7A8C4","#5CC8D7","#3B2F4A","파스텔 민트","바닐라 크림"],
    recommendedLogoStyles: ["플레이풀","모던"],
    recommendedTypography: ["둥글둥글한 산세리프","통통한 커스텀 레터링","간결한 고딕 본문체"],
    recommendedPersonality: ["즐거운","달콤한","경쾌한","사랑스러운"],
    recommendedKeywords: ["디저트","아이스크림","젤라또","케이크","빙수","디저트 카페"],
  },
  {
    name: "양조장/와이너리",
    seoSlug: "brewery-winery",
    category: "F&B",
    description: "라벨 한 장이 제품 경험의 시작인 업종으로, 원산지와 양조 방식의 이야기를 담아내는 것이 중요합니다. 전통적인 인장 느낌과 현대적 편집 감각 사이에서 톤을 정합니다.",
    recommendedColors: ["#5C1F2E","#C8A24A","#20211F","앰버","다크 올리브"],
    recommendedLogoStyles: ["클래식","에디토리얼"],
    recommendedTypography: ["인장 느낌의 세리프 엠블럼","자간이 넓은 대문자 로고타이프","라벨용 소형 산세리프"],
    recommendedPersonality: ["전통적인","깊이 있는","장인정신 있는","분위기 있는"],
    recommendedKeywords: ["양조장","와이너리","수제맥주","브루어리","전통주","와인"],
  },
  {
    name: "푸드트럭",
    seoSlug: "food-truck",
    category: "F&B",
    description: "차량 외관 자체가 간판인 업종으로, 멀리서 3초 안에 읽히는 대담한 형태가 필요합니다. 축제와 행사장에서 눈에 띄는 활기찬 표현을 선호합니다.",
    recommendedColors: ["#F2542D","#1B1B1B","머스타드 옐로우","오프 화이트"],
    recommendedLogoStyles: ["플레이풀","모던"],
    recommendedTypography: ["굵은 콘덴스드 대문자","레트로 느낌의 커스텀 레터링","메뉴판용 산세리프"],
    recommendedPersonality: ["활기찬","친근한","대담한","캐주얼한"],
    recommendedKeywords: ["푸드트럭","길거리 음식","이동식 매장","야시장","스트리트푸드","행사 케이터링"],
  },
  {
    name: "병원/의원/클리닉",
    seoSlug: "medical-clinic",
    category: "헬스케어/웰니스",
    description: "전문성과 안심을 동시에 전달해야 하는 업종으로, 과장 없이 정돈된 시각 언어가 곧 신뢰로 이어집니다. 진료과에 따라 차분함과 산뜻함의 균형을 조절합니다.",
    recommendedColors: ["#2E6DA4","#8FC7D9","#3E8E7E","소프트 블루","클린 화이트"],
    recommendedLogoStyles: ["모던","미니멀"],
    recommendedTypography: ["가독성 높은 고딕체","라운드 산세리프","정갈한 세리프 서브타이틀"],
    recommendedPersonality: ["신뢰감 있는","전문적인","위생적인","차분한","안심되는"],
    recommendedKeywords: ["병원","의원","클리닉","진료","의료","한의원"],
  },
  {
    name: "치과",
    seoSlug: "dental-clinic",
    category: "헬스케어/웰니스",
    description: "치료에 대한 불안을 덜어주는 것이 첫 과제인 업종으로, 청결함과 부드러움을 동시에 전달해야 합니다. 밝은 톤과 둥근 형태가 심리적 진입장벽을 낮춰 줍니다.",
    recommendedColors: ["#2FA8B5","#2E4756","#FFFFFF","민트 블루","소프트 화이트"],
    recommendedLogoStyles: ["모던","미니멀"],
    recommendedTypography: ["둥근 산세리프 워드마크","가독성 높은 고딕체","단정한 영문 서브타이틀"],
    recommendedPersonality: ["청결한","안심되는","섬세한","전문적인"],
    recommendedKeywords: ["치과","교정","임플란트","치아","덴탈","구강 건강"],
  },
  {
    name: "약국",
    seoSlug: "pharmacy",
    category: "헬스케어/웰니스",
    description: "정확함과 접근성이 동시에 필요한 업종으로, 간판이 멀리서도 즉시 식별되어야 합니다. 건강을 상징하는 단순 명료한 심볼이 잘 맞습니다.",
    recommendedColors: ["#2E7D5B","#1F3B2E","#F5F7F4","클린 그린","화이트"],
    recommendedLogoStyles: ["미니멀","모던"],
    recommendedTypography: ["명료한 고딕 헤드라인","높은 가독성의 본문 산세리프","단순한 영문 로고타이프"],
    recommendedPersonality: ["신뢰감 있는","정확한","친절한","건강한"],
    recommendedKeywords: ["약국","제약","건강기능식품","조제","의약품","드럭스토어"],
  },
  {
    name: "동물병원",
    seoSlug: "veterinary-clinic",
    category: "헬스케어/웰니스",
    description: "보호자의 걱정을 마주하는 업종으로, 의료적 신뢰와 다정한 태도를 함께 담아야 합니다. 진료의 전문성이 지나치게 차갑게 보이지 않도록 균형을 잡습니다.",
    recommendedColors: ["#4C9A8A","#F7C59F","#33413F","소프트 틸","웜 아이보리"],
    recommendedLogoStyles: ["모던","오가닉"],
    recommendedTypography: ["둥근 산세리프","가독성 좋은 고딕 본문체","부드러운 세리프 포인트"],
    recommendedPersonality: ["다정한","전문적인","안심되는","책임감 있는"],
    recommendedKeywords: ["동물병원","수의사","반려동물 진료","펫 클리닉","예방접종","동물 의료"],
  },
  {
    name: "뷰티/화장품",
    seoSlug: "beauty-cosmetics",
    category: "헬스케어/웰니스",
    description: "제품 용기와 진열대 위에서 바로 승부가 나는 업종으로, 성분에 대한 신뢰와 감각적인 무드를 함께 담아야 합니다. 여백과 절제로 고급스러움을 표현하는 방식을 선호합니다.",
    recommendedColors: ["#E8D5C9","#2B2B2B","#7A6A5F","누드 핑크","샴페인 골드"],
    recommendedLogoStyles: ["미니멀","럭셔리"],
    recommendedTypography: ["가는 획의 세리프","자간을 넓힌 대문자 로고타이프","섬세한 산세리프"],
    recommendedPersonality: ["세련된","깨끗한","섬세한","고급스러운"],
    recommendedKeywords: ["뷰티","화장품","코스메틱","스킨케어","메이크업","에스테틱"],
  },
  {
    name: "피트니스/헬스",
    seoSlug: "fitness-gym",
    category: "헬스케어/웰니스",
    description: "에너지와 지속성을 동시에 약속하는 업종으로, 강한 대비와 굵은 형태가 잘 어울립니다. 회원권과 SNS 콘텐츠에서 멀리서도 읽히는 힘이 필요합니다.",
    recommendedColors: ["#111111","#E63946","네온 라임","스틸 그레이"],
    recommendedLogoStyles: ["모던","테크"],
    recommendedTypography: ["굵은 콘덴스드 산세리프","각진 대문자 헤드라인","심플한 고딕 서브"],
    recommendedPersonality: ["역동적인","강인한","동기부여하는","전문적인"],
    recommendedKeywords: ["피트니스","헬스장","짐","PT","퍼스널 트레이닝","운동"],
  },
  {
    name: "요가/필라테스",
    seoSlug: "yoga-pilates-studio",
    category: "헬스케어/웰니스",
    description: "몸의 정렬과 마음의 회복을 함께 다루는 업종으로, 일반 헬스장보다 조용하고 절제된 인상이 요구됩니다. 가는 선과 넉넉한 여백을 활용한 표현이 잘 맞습니다.",
    recommendedColors: ["#A79A88","#3E4A42","#F2EDE6","세이지 그린","머스크 베이지"],
    recommendedLogoStyles: ["미니멀","오가닉"],
    recommendedTypography: ["가는 획의 산세리프","자간이 넓은 소문자 로고타이프","단정한 세리프 서브"],
    recommendedPersonality: ["차분한","균형 잡힌","섬세한","회복적인"],
    recommendedKeywords: ["요가","필라테스","스튜디오","명상","스트레칭","코어 운동"],
  },
  {
    name: "리테일/쇼핑몰",
    seoSlug: "retail-store",
    category: "리테일",
    description: "상품 구성이 자주 바뀌어도 흔들리지 않는 얼굴이 필요한 업종으로, 상세페이지와 패키지, 배송 박스까지 반복 노출되는 로고의 확장성이 중요합니다. 깔끔하고 기억하기 쉬운 표현을 선호합니다.",
    recommendedColors: ["#111111","#F2603C","딥 차콜","웜 오렌지","오프 화이트"],
    recommendedLogoStyles: ["모던","미니멀"],
    recommendedTypography: ["굵은 산세리프 헤드라인","간결한 워드마크","가독성 좋은 본문 고딕"],
    recommendedPersonality: ["실용적인","친근한","트렌디한","믿을 수 있는"],
    recommendedKeywords: ["리테일","쇼핑몰","온라인 스토어","편집숍","이커머스","매장"],
  },
  {
    name: "패션/의류",
    seoSlug: "fashion-apparel",
    category: "리테일",
    description: "시즌마다 이미지가 바뀌어도 중심을 잡아주는 워드마크가 핵심인 업종으로, 라벨과 택, 룩북에서 작게 쓰일 때의 완성도가 중요합니다. 태도가 분명한 미니멀 표현을 선호합니다.",
    recommendedColors: ["#0A0A0A","#C0392B","#FFFFFF","모노 블랙","머스타드"],
    recommendedLogoStyles: ["미니멀","에디토리얼"],
    recommendedTypography: ["자간이 넓은 대문자 워드마크","콘트라스트 강한 세리프","깔끔한 산세리프 라벨체"],
    recommendedPersonality: ["감각적인","자신감 있는","동시대적인","절제된"],
    recommendedKeywords: ["패션","의류","옷","브랜드 의류","스트릿웨어","여성복"],
  },
  {
    name: "주얼리/액세서리",
    seoSlug: "jewelry",
    category: "리테일",
    description: "작은 각인과 케이스 위에서 완성도가 드러나는 업종으로, 선의 굵기 하나까지 정교해야 합니다. 절제된 고급스러움을 담는 표현을 선호합니다.",
    recommendedColors: ["#C9A227","#1A1A1A","#6E7B78","샴페인 골드","펄 화이트"],
    recommendedLogoStyles: ["럭셔리","미니멀"],
    recommendedTypography: ["가는 획의 세리프","자간을 크게 벌린 대문자 워드마크","섬세한 산세리프"],
    recommendedPersonality: ["고급스러운","정교한","우아한","특별한"],
    recommendedKeywords: ["주얼리","액세서리","반지","목걸이","예물","귀금속"],
  },
  {
    name: "가구/홈퍼니싱",
    seoSlug: "furniture-home",
    category: "리테일",
    description: "소재와 비례의 감각을 파는 업종으로, 제품 사진 옆에 놓였을 때 조용히 어울리는 아이덴티티가 필요합니다. 자연 소재의 질감을 연상시키는 톤을 선호합니다.",
    recommendedColors: ["#8B6B4A","#EFE9E1","#5A6B5D","월넛 브라운","차콜 그레이"],
    recommendedLogoStyles: ["미니멀","오가닉"],
    recommendedTypography: ["여백감 있는 산세리프","단정한 세리프 워드마크","카탈로그용 본문체"],
    recommendedPersonality: ["차분한","견고한","실용적인","세련된"],
    recommendedKeywords: ["가구","홈퍼니싱","원목 가구","리빙","인테리어 소품","가구 공방"],
  },
  {
    name: "플라워샵",
    seoSlug: "flower-shop",
    category: "리테일",
    description: "계절과 감정을 함께 파는 업종으로, 포장지와 카드, 리본까지 이어지는 섬세한 디테일이 중요합니다. 꽃 자체를 가리지 않는 은은한 아이덴티티를 선호합니다.",
    recommendedColors: ["#E7A6B6","#4F6B4A","#2F2A2E","더스티 로즈","크림 아이보리"],
    recommendedLogoStyles: ["오가닉","미니멀"],
    recommendedTypography: ["가는 획의 세리프","손글씨 느낌의 스크립트체","카드용 산세리프"],
    recommendedPersonality: ["섬세한","서정적인","우아한","따뜻한"],
    recommendedKeywords: ["플라워샵","꽃집","꽃다발","화훼","플로리스트","부케"],
  },
  {
    name: "서점/문구",
    seoSlug: "bookstore-stationery",
    category: "리테일",
    description: "머무는 시간이 곧 매출로 이어지는 업종으로, 큐레이션의 취향이 브랜드 그 자체가 됩니다. 활자 중심의 편집 감각이 잘 어울립니다.",
    recommendedColors: ["#2B2A26","#EDE6D6","#9C4A2F","잉크 네이비","크래프트 베이지"],
    recommendedLogoStyles: ["에디토리얼","클래식"],
    recommendedTypography: ["활판 느낌의 세리프","자간이 정돈된 워드마크","라벨용 산세리프"],
    recommendedPersonality: ["차분한","지적인","취향 있는","다정한"],
    recommendedKeywords: ["서점","책방","문구점","독립서점","스테이셔너리","도서"],
  },
  {
    name: "반려동물",
    seoSlug: "pet-care",
    category: "리테일",
    description: "보호자의 애정과 반려동물의 안전을 함께 다루는 업종으로, 다정하면서도 위생과 품질에 대한 믿음을 주어야 합니다. 부드러운 곡선과 따뜻한 색이 잘 맞습니다.",
    recommendedColors: ["#F4A26B","#4E7C59","#5B4B3A","소프트 코랄","크림"],
    recommendedLogoStyles: ["플레이풀","오가닉"],
    recommendedTypography: ["둥근 산세리프","손글씨 느낌의 포인트 서체","가독성 좋은 고딕 본문체"],
    recommendedPersonality: ["다정한","안전한","활기찬","믿음직한"],
    recommendedKeywords: ["반려동물","펫","강아지","고양이","펫샵","애견 용품"],
  },
  {
    name: "컨설팅",
    seoSlug: "consulting",
    category: "전문 서비스",
    description: "무형의 전문성을 판매하는 업종으로, 제안서와 명함에서 곧바로 격을 전달하는 정제된 아이덴티티가 필요합니다. 장식을 덜어낸 구조적 표현을 선호합니다.",
    recommendedColors: ["#1C2B39","#7A8B99","딥 인디고","웜 그레이"],
    recommendedLogoStyles: ["미니멀","모던"],
    recommendedTypography: ["절제된 산세리프 워드마크","권위감 있는 세리프","문서용 고딕 본문체"],
    recommendedPersonality: ["전문적인","논리적인","신뢰감 있는","객관적인"],
    recommendedKeywords: ["컨설팅","전략","경영 자문","비즈니스 코칭","조직 진단","기업 자문"],
  },
  {
    name: "법률/법무법인",
    seoSlug: "law-firm",
    category: "전문 서비스",
    description: "의뢰인의 중대한 사안을 다루는 업종으로, 절제된 형식미가 곧 권위와 신뢰로 읽힙니다. 장식을 최소화한 워드마크 중심의 아이덴티티를 선호합니다.",
    recommendedColors: ["#16283C","#B79A5B","딥 네이비","웜 그레이"],
    recommendedLogoStyles: ["클래식","미니멀"],
    recommendedTypography: ["권위감 있는 세리프 워드마크","자간이 넓은 대문자 로고타이프","문서용 고딕 본문체"],
    recommendedPersonality: ["신뢰감 있는","권위 있는","치밀한","전문적인"],
    recommendedKeywords: ["법률","변호사","법무법인","로펌","소송","법률 자문"],
  },
  {
    name: "회계/세무",
    seoSlug: "accounting-firm",
    category: "전문 서비스",
    description: "숫자의 정확성과 기밀 유지가 핵심 가치인 업종으로, 정돈된 구조와 명료한 대비가 어울립니다. 보고서와 서식 안에서 조용히 신뢰를 쌓는 디자인을 선호합니다.",
    recommendedColors: ["#1E3A5F","#2F8F6F","슬레이트 그레이","오프 화이트"],
    recommendedLogoStyles: ["미니멀","모던"],
    recommendedTypography: ["숫자 가독성이 좋은 산세리프","격자에 맞춘 워드마크","단정한 세리프 서브"],
    recommendedPersonality: ["정확한","신중한","전문적인","성실한"],
    recommendedKeywords: ["회계","세무","세무사","기장","절세","재무 관리"],
  },
  {
    name: "마케팅/광고대행사",
    seoSlug: "marketing-agency",
    category: "전문 서비스",
    description: "자기 브랜드가 곧 실력 증명서인 업종으로, 제안 자료 첫 장에서 감각을 증명해야 합니다. 대담한 타이포그래피와 유연한 컬러 운용을 선호합니다.",
    recommendedColors: ["#FF4D3D","#111827","일렉트릭 퍼플","오프 화이트"],
    recommendedLogoStyles: ["모던","에디토리얼"],
    recommendedTypography: ["굵은 산세리프 헤드라인","커스텀 레터링 워드마크","깔끔한 본문 고딕"],
    recommendedPersonality: ["창의적인","대담한","전략적인","기민한"],
    recommendedKeywords: ["마케팅","광고대행사","퍼포먼스 마케팅","브랜딩 에이전시","캠페인","콘텐츠 마케팅"],
  },
  {
    name: "금융",
    seoSlug: "finance",
    category: "전문 서비스",
    description: "자산과 약속을 다루는 업종으로, 절제된 형태와 명확한 구조가 곧 신뢰의 근거가 됩니다. 앱 아이콘처럼 작은 크기에서도 또렷하게 읽혀야 합니다.",
    recommendedColors: ["#0F2E4C","#1E7A5A","딥 네이비","실버 그레이"],
    recommendedLogoStyles: ["모던","클래식","미니멀"],
    recommendedTypography: ["기하학적 산세리프 워드마크","안정적인 세리프","숫자 가독성이 좋은 본문체"],
    recommendedPersonality: ["신뢰감 있는","안정적인","투명한","전문적인"],
    recommendedKeywords: ["금융","핀테크","투자","자산관리","대출","증권"],
  },
  {
    name: "보험",
    seoSlug: "insurance",
    category: "전문 서비스",
    description: "눈에 보이지 않는 약속을 파는 업종으로, 안정감과 이해하기 쉬운 설명이 브랜드 신뢰를 만듭니다. 보호를 상징하는 단순한 기하 형태가 잘 맞습니다.",
    recommendedColors: ["#164E63","#3D8B6E","트러스트 블루","웜 그레이"],
    recommendedLogoStyles: ["모던","클래식"],
    recommendedTypography: ["안정적인 산세리프 워드마크","가독성 높은 본문 고딕","단정한 세리프 서브"],
    recommendedPersonality: ["안정적인","신뢰감 있는","친절한","책임감 있는"],
    recommendedKeywords: ["보험","보험 설계","손해보험","생명보험","보장 분석","보험 대리점"],
  },
  {
    name: "여행/숙박",
    seoSlug: "travel-hospitality",
    category: "라이프스타일",
    description: "떠나기 전의 기대감을 파는 업종으로, 장소의 고유한 정서를 한 장의 심볼로 압축하는 작업이 중요합니다. 예약 화면부터 객실 사인까지 폭넓게 쓰일 확장성이 필요합니다.",
    recommendedColors: ["#2C5F6B","#E4D5B7","#3F4A3C","오션 블루","선셋 오렌지"],
    recommendedLogoStyles: ["오가닉","에디토리얼","미니멀"],
    recommendedTypography: ["여백감 있는 세리프","자간이 넓은 영문 로고타이프","단정한 산세리프 본문체"],
    recommendedPersonality: ["여유로운","설레는","친절한","기억에 남는"],
    recommendedKeywords: ["여행","숙박","호텔","펜션","게스트하우스","스테이"],
  },
  {
    name: "사진/영상 스튜디오",
    seoSlug: "photography-studio",
    category: "라이프스타일",
    description: "결과물이 주인공이어야 하는 업종으로, 로고는 작품 위에 얹혔을 때 방해가 되지 않아야 합니다. 워터마크로 작게 쓰일 때의 가독성이 특히 중요합니다.",
    recommendedColors: ["#141414","#EDEAE4","모노 그레이","웜 앰버"],
    recommendedLogoStyles: ["미니멀","에디토리얼"],
    recommendedTypography: ["자간이 넓은 대문자 워드마크","가는 획의 산세리프","포트폴리오용 세리프 캡션"],
    recommendedPersonality: ["감각적인","정제된","서사적인","전문적인"],
    recommendedKeywords: ["사진","스튜디오","포토그래퍼","영상 제작","프로필 촬영","포토그래피"],
  },
  {
    name: "웨딩/이벤트 기획",
    seoSlug: "wedding-event-planning",
    category: "라이프스타일",
    description: "일생에 한 번인 순간을 설계하는 업종으로, 청첩장부터 현장 사인물까지 이어지는 섬세한 아이덴티티가 필요합니다. 우아함과 따뜻함을 함께 담는 표현을 선호합니다.",
    recommendedColors: ["#D8C3B0","#7B2E3E","#2F2A28","샴페인 골드","더스티 로즈"],
    recommendedLogoStyles: ["럭셔리","클래식"],
    recommendedTypography: ["섬세한 스크립트체","가는 획의 세리프","자간이 넓은 대문자 서브타이틀"],
    recommendedPersonality: ["우아한","섬세한","따뜻한","기억에 남는"],
    recommendedKeywords: ["웨딩","결혼식","이벤트 기획","웨딩플래너","행사 연출","파티 기획"],
  },
  {
    name: "세탁/드라이클리닝",
    seoSlug: "laundry-dry-cleaning",
    category: "라이프스타일",
    description: "맡긴 옷을 안심하고 되찾는 경험을 파는 업종으로, 청결함과 정확한 관리 이미지가 핵심입니다. 간판과 세탁물 태그에서 또렷하게 보이는 단순한 마크가 잘 맞습니다.",
    recommendedColors: ["#2F6FB5","#F4F7FA","#2C3E50","프레시 블루","소프트 화이트"],
    recommendedLogoStyles: ["미니멀","모던"],
    recommendedTypography: ["단순한 고딕 워드마크","둥근 산세리프","안내문용 본문 서체"],
    recommendedPersonality: ["청결한","꼼꼼한","편리한","믿을 수 있는"],
    recommendedKeywords: ["세탁","드라이클리닝","빨래","코인세탁","런드리","셔츠 세탁"],
  },
  {
    name: "청소/홈케어",
    seoSlug: "cleaning-services",
    category: "라이프스타일",
    description: "낯선 사람이 집과 사무실에 들어가는 서비스인 만큼, 안전과 정직함의 인상이 계약을 좌우하는 업종입니다. 산뜻하고 명료한 시각 언어를 선호합니다.",
    recommendedColors: ["#3AA675","#EAF5EF","#28394A","프레시 그린","클린 화이트"],
    recommendedLogoStyles: ["모던","미니멀"],
    recommendedTypography: ["또렷한 산세리프 워드마크","둥근 고딕 서브타이틀","안내용 본문체"],
    recommendedPersonality: ["정직한","꼼꼼한","산뜻한","친절한"],
    recommendedKeywords: ["청소","입주청소","홈클리닝","사무실 청소","가사 서비스","정리수납"],
  },
  {
    name: "교육",
    seoSlug: "education",
    category: "교육",
    description: "학습자와 보호자 양쪽의 신뢰를 동시에 얻어야 하는 업종으로, 성장과 체계라는 두 인상을 균형 있게 담아야 합니다. 밝되 가볍지 않은 톤을 선호합니다.",
    recommendedColors: ["#1F5FA8","#F5A623","트러스트 블루","웜 옐로우"],
    recommendedLogoStyles: ["모던","클래식"],
    recommendedTypography: ["또렷한 고딕 헤드라인","안정적인 세리프","라운드 산세리프 서브"],
    recommendedPersonality: ["신뢰감 있는","체계적인","성장을 돕는","친근한"],
    recommendedKeywords: ["교육","학원","과외","스터디","강의","입시"],
  },
  {
    name: "유치원/어린이집",
    seoSlug: "kindergarten-childcare",
    category: "교육",
    description: "아이의 즐거움과 보호자의 안심을 동시에 얻어야 하는 업종으로, 밝은 색과 둥근 형태가 자연스럽게 어울립니다. 유치해 보이지 않도록 정돈된 균형을 잡는 것이 관건입니다.",
    recommendedColors: ["#FFB627","#4CAF7D","#3C4A63","스카이 블루","크림 화이트"],
    recommendedLogoStyles: ["플레이풀","오가닉"],
    recommendedTypography: ["둥근 산세리프","손글씨 느낌의 포인트 서체","안내문용 고딕 본문체"],
    recommendedPersonality: ["따뜻한","안전한","즐거운","돌보는"],
    recommendedKeywords: ["유치원","어린이집","보육","키즈","놀이학교","유아 교육"],
  },
  {
    name: "대학/고등교육",
    seoSlug: "higher-education",
    category: "교육",
    description: "역사와 학문적 권위를 전달해야 하는 업종으로, 엠블럼 형태의 전통적 아이덴티티가 여전히 강한 설득력을 가집니다. 디지털 적용을 위한 단순화 버전을 함께 설계합니다.",
    recommendedColors: ["#1B3D6D","#8C1D2C","아카데믹 골드","스톤 그레이"],
    recommendedLogoStyles: ["클래식","에디토리얼"],
    recommendedTypography: ["엠블럼용 세리프","격식 있는 대문자 로고타이프","자료용 고딕 본문체"],
    recommendedPersonality: ["권위 있는","전통 있는","학문적인","신뢰감 있는"],
    recommendedKeywords: ["대학","대학교","고등교육","캠퍼스","연구기관","학부 과정"],
  },
  {
    name: "온라인강의/에듀테크",
    seoSlug: "online-course-edtech",
    category: "교육",
    description: "화면 안에서만 만나는 업종으로, 앱 아이콘과 강의 썸네일에서 즉시 구분되는 선명한 아이덴티티가 필요합니다. 학습 동기를 자극하는 밝고 명료한 톤을 선호합니다.",
    recommendedColors: ["#4A5CF5","#12B886","바이올렛","라이트 그레이"],
    recommendedLogoStyles: ["모던","테크"],
    recommendedTypography: ["기하학적 산세리프","굵은 썸네일용 헤드라인","가독성 좋은 UI 본문체"],
    recommendedPersonality: ["명료한","혁신적인","동기부여하는","친근한"],
    recommendedKeywords: ["온라인 강의","에듀테크","이러닝","인강","학습 플랫폼","온라인 클래스"],
  },
  {
    name: "IT/스타트업",
    seoSlug: "it-startup",
    category: "기술",
    description: "빠른 성장과 문제 해결 역량을 압축해 보여줘야 하는 업종으로, 서비스 화면과 투자 자료, 채용 페이지 어디에 놓여도 확장되는 아이덴티티가 필요합니다. 군더더기 없는 현대적 인상을 선호합니다.",
    recommendedColors: ["#3B5BFF","#101827","일렉트릭 블루","쿨 그레이"],
    recommendedLogoStyles: ["모던","테크","미니멀"],
    recommendedTypography: ["기하학적 산세리프","굵은 헤드라인 그로테스크","모노스페이스 포인트 서체"],
    recommendedPersonality: ["혁신적인","명료한","민첩한","전문적인"],
    recommendedKeywords: ["IT","스타트업","테크","플랫폼","앱 서비스","개발사"],
  },
  {
    name: "SaaS/소프트웨어",
    seoSlug: "saas-software",
    category: "기술",
    description: "제품 UI 안에 상시 노출되는 로고가 필요한 업종으로, 작은 크기와 다크 모드에서도 무너지지 않는 형태가 중요합니다. 기능적이고 확장 가능한 시스템형 아이덴티티를 선호합니다.",
    recommendedColors: ["#2563EB","#0F172A","클라우드 그레이","민트 액센트"],
    recommendedLogoStyles: ["테크","미니멀","모던"],
    recommendedTypography: ["UI 친화적인 산세리프","기하학적 워드마크","모노스페이스 코드체"],
    recommendedPersonality: ["명료한","효율적인","신뢰감 있는","확장성 있는"],
    recommendedKeywords: ["SaaS","소프트웨어","B2B 솔루션","클라우드","구독 서비스","업무 툴"],
  },
  {
    name: "AI/딥테크",
    seoSlug: "ai-deeptech",
    category: "기술",
    description: "아직 낯선 기술을 설득해야 하는 업종으로, 첨단성과 통제 가능한 안정감을 동시에 보여줘야 합니다. 추상적인 기하 도형과 그라데이션 표현이 잘 맞습니다.",
    recommendedColors: ["#6E56F8","#0B0B12","#E6E8F0","일렉트릭 시안","딥 퍼플"],
    recommendedLogoStyles: ["테크","모던","미니멀"],
    recommendedTypography: ["기하학적 산세리프","자간이 넓은 대문자 로고타이프","모노스페이스 포인트 서체"],
    recommendedPersonality: ["혁신적인","정밀한","미래지향적인","전문적인"],
    recommendedKeywords: ["AI","인공지능","딥테크","머신러닝","데이터 분석","연구개발"],
  },
  {
    name: "게임/e스포츠",
    seoSlug: "gaming-esports",
    category: "기술",
    description: "팬덤이 로고를 굿즈와 프로필 이미지로 소비하는 업종으로, 강한 실루엣과 상징성이 핵심입니다. 스트리밍 화면과 유니폼 어디에서나 강렬하게 읽혀야 합니다.",
    recommendedColors: ["#7B2FF7","#0D0D12","네온 그린","일렉트릭 블루"],
    recommendedLogoStyles: ["테크","플레이풀"],
    recommendedTypography: ["각진 커스텀 레터링","굵은 이탤릭 산세리프","화면용 고딕 본문체"],
    recommendedPersonality: ["강렬한","경쟁적인","몰입감 있는","개성 있는"],
    recommendedKeywords: ["게임","e스포츠","게임 스튜디오","프로게임단","스트리밍","인디게임"],
  },
  {
    name: "제조업",
    seoSlug: "manufacturing",
    category: "제조/산업",
    description: "B2B 거래와 품질 인증이 중심인 업종으로, 도면과 설비 명판에 새겨도 형태가 무너지지 않는 견고한 마크가 필요합니다. 과장을 덜어낸 기능적 표현을 선호합니다.",
    recommendedColors: ["#243447","#F26722","인더스트리얼 그레이","스틸 블루"],
    recommendedLogoStyles: ["모던","테크","미니멀"],
    recommendedTypography: ["각진 산세리프 워드마크","콘덴스드 대문자 헤드라인","정보 전달용 고딕 본문체"],
    recommendedPersonality: ["견고한","정밀한","신뢰감 있는","실용적인"],
    recommendedKeywords: ["제조","공장","생산","부품","OEM","산업 설비"],
  },
  {
    name: "물류/배송",
    seoSlug: "logistics-delivery",
    category: "제조/산업",
    description: "속도와 정확한 도착이 약속의 전부인 업종으로, 차량 랩핑과 박스 테이프에서 멀리서도 식별되어야 합니다. 방향성과 움직임을 담은 형태를 선호합니다.",
    recommendedColors: ["#F59E0B","#12325E","스피드 레드","뉴트럴 그레이"],
    recommendedLogoStyles: ["모던","테크"],
    recommendedTypography: ["굵은 콘덴스드 산세리프","이탤릭 워드마크","송장용 고딕 본문체"],
    recommendedPersonality: ["신속한","정확한","믿을 수 있는","체계적인"],
    recommendedKeywords: ["물류","배송","택배","풀필먼트","운송","화물"],
  },
  {
    name: "자동차정비",
    seoSlug: "auto-repair",
    category: "제조/산업",
    description: "기술력에 대한 신뢰와 투명한 견적이 재방문을 만드는 업종으로, 작업복과 간판에 어울리는 견고한 마크가 필요합니다. 기계적 정밀함을 연상시키는 표현을 선호합니다.",
    recommendedColors: ["#B32026","#1C1C1E","스틸 그레이","세이프티 옐로우"],
    recommendedLogoStyles: ["모던","클래식"],
    recommendedTypography: ["각진 대문자 워드마크","굵은 콘덴스드 산세리프","안내판용 고딕체"],
    recommendedPersonality: ["견고한","정직한","숙련된","신뢰감 있는"],
    recommendedKeywords: ["자동차정비","카센터","차량 수리","공업사","차량 관리","튜닝"],
  },
  {
    name: "부동산",
    seoSlug: "real-estate",
    category: "부동산/건설",
    description: "큰 금액의 의사결정을 다루는 업종으로, 안정감과 정확함이 브랜드의 첫인상을 좌우합니다. 지역 밀착형과 프리미엄형 사이에서 무게감을 조절합니다.",
    recommendedColors: ["#1B3A5C","#C8A96A","#F0EDE8","네이비","웜 골드"],
    recommendedLogoStyles: ["클래식","모던"],
    recommendedTypography: ["안정적인 세리프 워드마크","정갈한 고딕 본문체","자간이 넓은 영문 로고타이프"],
    recommendedPersonality: ["신뢰감 있는","안정적인","전문적인","성실한"],
    recommendedKeywords: ["부동산","공인중개사","중개","분양","임대","매물"],
  },
  {
    name: "건축사무소",
    seoSlug: "architecture-firm",
    category: "부동산/건설",
    description: "도면과 준공 사진이 곧 포트폴리오인 업종으로, 로고는 작품의 형태 언어와 충돌하지 않아야 합니다. 격자와 비례에 기반한 절제된 아이덴티티를 선호합니다.",
    recommendedColors: ["#2B2B2B","#E8E4DD","콘크리트 그레이","딥 올리브"],
    recommendedLogoStyles: ["미니멀","에디토리얼"],
    recommendedTypography: ["기하학적 산세리프 워드마크","자간이 넓은 대문자 로고타이프","도면용 본문 고딕"],
    recommendedPersonality: ["정제된","구조적인","전문적인","동시대적인"],
    recommendedKeywords: ["건축","건축사무소","설계","건축가","공간 설계","설계 감리"],
  },
  {
    name: "인테리어/공간디자인",
    seoSlug: "interior-design",
    category: "부동산/건설",
    description: "완성된 공간의 무드가 곧 브랜드의 증거인 업종으로, 시공 사진과 나란히 놓여도 어울리는 차분한 아이덴티티가 필요합니다. 소재감을 살린 색 운용을 선호합니다.",
    recommendedColors: ["#A08A72","#F1ECE4","#33302C","웜 그레이","딥 그린"],
    recommendedLogoStyles: ["미니멀","에디토리얼"],
    recommendedTypography: ["여백감 있는 산세리프","단정한 세리프 워드마크","제안서용 본문체"],
    recommendedPersonality: ["세련된","차분한","감각적인","섬세한"],
    recommendedKeywords: ["인테리어","공간디자인","리모델링","홈스타일링","상업공간","인테리어 시공"],
  },
  {
    name: "건설/시공",
    seoSlug: "construction",
    category: "부동산/건설",
    description: "안전과 공기 준수가 신뢰의 척도인 업종으로, 현수막과 안전모, 차량에 적용해도 형태가 유지되는 단순한 마크가 필요합니다. 무게감 있는 색과 굵은 획을 선호합니다.",
    recommendedColors: ["#F2A600","#2B3440","콘크리트 그레이","딥 네이비"],
    recommendedLogoStyles: ["모던","미니멀"],
    recommendedTypography: ["굵은 대문자 산세리프","각진 워드마크","현장 안내용 고딕체"],
    recommendedPersonality: ["견고한","안전한","성실한","신뢰감 있는"],
    recommendedKeywords: ["건설","시공","토목","종합건설","건설 현장","건축 시공"],
  },
  {
    name: "예술/디자인",
    seoSlug: "art-design",
    category: "공공/문화",
    description: "결과물 자체가 포트폴리오인 업종으로, 로고는 작품을 가리지 않으면서 작가의 태도를 드러내야 합니다. 타이포그래피 중심의 절제된 아이덴티티를 선호합니다.",
    recommendedColors: ["#111111","#F4F1EA","#C24A2C","잉크 블랙","페이퍼 화이트"],
    recommendedLogoStyles: ["에디토리얼","미니멀"],
    recommendedTypography: ["콘트라스트 강한 세리프","실험적인 커스텀 레터링","중립적인 산세리프 본문체"],
    recommendedPersonality: ["창의적인","실험적인","감각적인","독창적인"],
    recommendedKeywords: ["예술","디자인","디자인 스튜디오","작가","갤러리","크리에이티브"],
  },
  {
    name: "비영리/공공",
    seoSlug: "nonprofit-public",
    category: "공공/문화",
    description: "설득보다 공감으로 움직이는 업종으로, 누구에게나 읽히는 접근성과 진정성이 최우선입니다. 밝고 열린 인상의 단순한 심볼이 잘 맞습니다.",
    recommendedColors: ["#2A6E5A","#3B72B8","웜 옐로우","뉴트럴 그레이"],
    recommendedLogoStyles: ["모던","오가닉"],
    recommendedTypography: ["가독성 높은 고딕체","둥근 산세리프","단정한 본문 서체"],
    recommendedPersonality: ["진정성 있는","포용적인","투명한","희망적인"],
    recommendedKeywords: ["비영리","공공기관","재단","사회적기업","NGO","공익 캠페인"],
  },
];

async function main() {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
  const prisma = new PrismaClient({ adapter });

  for (const industry of INDUSTRIES) {
    const data = {
      seoSlug: industry.seoSlug,
      category: industry.category,
      description: industry.description,
      recommendedColors: industry.recommendedColors,
      recommendedLogoStyles: industry.recommendedLogoStyles,
      recommendedTypography: industry.recommendedTypography,
      recommendedPersonality: industry.recommendedPersonality,
      recommendedKeywords: industry.recommendedKeywords,
    };
    await prisma.industry.upsert({
      where: { name: industry.name },
      create: { name: industry.name, ...data },
      update: data,
    });
  }

  const categoryCount = new Set(INDUSTRIES.map((i) => i.category)).size;
  console.log(`Seeded industries: ${INDUSTRIES.length} across ${categoryCount} categories`);
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
